### ISSUE TITLE
TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

### ISSUE THREAD

**Issue by Davidoseq** [wingify/vwo-node-sdk#30]
Hello, 
I can't import enum LogLevelEnum because of **isolatedModules**. Can you look at it please?

https://codesandbox.io/s/strange-bas-borkk?file=/src/App.tsx

Reason is here: 
https://stackoverflow.com/questions/40227401/const-enum-in-typescript

**Remove the const** modifier should fix the problem.

Thank you very much.

**Comment by softvar** [comment]
As mentioned in #29 , please use:
```js
vwoSDK.LogLevelEnum.INFO
```

instead of importing `LogLevelEnum` and using it.
`LogLevelEnum` is exposed and has typings on vwoSDK

**Comment by softvar** [comment]
Closing the issue as it is fixed in the latest versions! Please let us know if you face any problems.
