### ISSUE TITLE
Promise for isFeatureEnabled is not always resolved

### ISSUE THREAD

**Issue by jbalbien** [wingify/vwo-node-sdk#34]
https://github.com/wingify/vwo-node-sdk/blob/v1.32.1/lib/api/isFeatureEnabled.js#L206 can return a boolean value, but https://github.com/wingify/vwo-node-sdk/blob/v1.32.1/lib/VWO.js#L389 only expects the return value to be an object. This results in the promise not being resolved.

**Comment by softvar** [comment]
Thanks for reporting this. We have fixed the issue. Please try using `v1.32.2` and let us know if it works.

**Comment by jbalbien** [comment]
Confirmed fixed - thanks!

**Comment by softvar** [comment]
Hey @jbalbien,

We are currently looking into it and will revert with a fix soon. We are testing all the possible scenarios at our end.

**Comment by softvar** [comment]
Hey @jbalbien ,

We have successfully released a new version `v1.33.0` which has all the cases covered for dealing with promises when `isFeatureEnabled` is used. Please update your application and point to the latest version of VWO Node SDK. We appreciate your patience.
