### ISSUE TITLE
⚠️ You need to resolve these merge conflicts and redeploy immediately

### ISSUE THREAD

**Issue by shanemac10** [wingify/vwo-node-sdk#54]
You have 2 merge conflicts that are being served to clients and breaking the functionality. Please resolve, rebuild, and redeploy ASAP! Thank you!

https://github.com/wingify/vwo-node-sdk/blob/c313f6fcfa7c51b0b326caf9bb6509c3fb46d73d/dist/vwo-javascript-sdk.min.js#L29

**Comment by shanemac10** [comment]
https://cdn.jsdelivr.net/npm/vwo-node-sdk@1/dist/vwo-javascript-sdk.min.js

**Comment by shanemac10** [comment]
![Uploading Screenshot 2023-11-15 at 10.56.12 AM.png…]()

**Comment by shanemac10** [comment]
![Screenshot 2023-11-15 at 10 56 12 AM](https://github.com/wingify/vwo-node-sdk/assets/18744254/81b88758-d8b0-4190-a431-d8e3d92db0cd)

**Comment by shanemac10** [comment]
@softvar

**Comment by rohitesh-wingify** [comment]
Hey @shanemac10 . Yes. We are on it.

**Comment by rohitesh-wingify** [comment]
Hey @shanemac10, can you please check at your end, if this is resolved now?

**Comment by shanemac10** [comment]
@rohitesh-wingify No, it's still the same file with the same issue. Nothing changed.

**Comment by rohitesh-wingify** [comment]
@shanemac10 Can you please check for the latest version? It is resolved it in the latest version.

**Comment by shanemac10** [comment]
No, the plugin is using this URL

https://cdn.jsdelivr.net/npm/vwo-node-sdk@1/dist/vwo-javascript-sdk.min.js

**Comment by rohitesh-wingify** [comment]
@shanemac10 Can you please upgrade the plugin to use the latest version? That has the issue resolved.

**Comment by shanemac10** [comment]
@rohitesh-wingify No, it's not showing as having an update available.

**Comment by rohitesh-wingify** [comment]
@shanemac10 Can you please share your email ID so I can reach out to you?

**Comment by shanemac10** [comment]
@rohitesh-wingify No thank you.

 Let me clarify, my site had the latest plugin update as 4.1 from 2 days ago, and I'm not seeing a new one to be updated to. But either way, the issue appears to be with your `.../dist/vwo-javascript-sdk*` files having unresolved merge conflicts in them. These conflicts are still in the master repo, so perhaps start by resolving them and committing those to master.

**Comment by softvar** [comment]
Hi @shanemac10 ,

We have published a new version as the earlier one was faulty.
The URL which you're using i.e. https://cdn.jsdelivr.net/npm/vwo-node-sdk@1/dist/vwo-javascript-sdk.min.js is reflecting the changes. Can you please try and confirm?

Also, I would like to highlight that if you're using vwo-node-sdk@1 in the URL, that means that whenever we will be pushing any new version (and after jsdelivr CDN, a third-party CDN,  updates the cache) you will get the latest code which was published on GitHub and NPM. You can also provide the version manually if you're interested in updating the SDK only when you would like to do so like [vwo-node-sdk@1.63.2.](mailto:vwo-node-sdk@1.63.2.)

Let us know if you have any further questions.

**Comment by shanemac10** [comment]
Thanks for getting this knocked out so quickly
