### ISSUE TITLE
vwoSDK.getAndUpdateSettingsFile is not a function

### ISSUE THREAD

**Issue by EdiGal91** [wingify/vwo-node-sdk#8]
I'm trying to configure a web-hooks following this documentation:
https://developers.vwo.com/reference#fullstack-configure-webhooks

The note section say:
"getAndUpdateSettingsFile - is only available in Node.js SDK from v1.10+ onwards"

I'm using the last version of the package 1.10, but there is no "getAndUpdateSettingsFile" function there.

![image](https://user-images.githubusercontent.com/47693118/103272053-86dd4d80-49c4-11eb-8b40-e19bbea52754.png)

![image](https://user-images.githubusercontent.com/47693118/103272094-9e1c3b00-49c4-11eb-9c9a-00f72e9e5f84.png)

![image](https://user-images.githubusercontent.com/47693118/103272151-bf7d2700-49c4-11eb-8478-248340a69761.png)

**Comment by softvar** [comment]
Hey @EdiGal91,

`getAndUpdateSettingsFile` is available on VWO Client-Instance and not on VWO-SDK.
Please use:
```javascript
var vwoSDK = require('vwo-node-sdk');

var vwoClientInstance = vwoSDK.launch({
  settingsFile: settingsFile
});

vwoClientInstance.getAndUpdateSettingsFile().then(_data => console.log(data));
```

Please let us know if you face any issues with this.
